version: '3.8'

services:
  backend:
    container_name: milvus_admin_back
    build: ./backend
    ports:
      - "8080:8080"
    volumes:
      - ./backend:/app
    environment:
      - PYTHONUNBUFFERED=1

  frontend:
    container_name: milvus_admin_front
    build: ./frontend
    ports:
      - "3000:80"
    depends_on:
      - backend

  # Optionally add Milvus later
  # milvus:
  #   image: milvusdb/milvus:v2.4.0
  #   ports:
  #     - "19530:19530"
